### PR TITLE
AMLMX: misc commits

### PR DESCRIPTION
**Pull request by kszaq**
Hi @chewitt. Thank you for providing the AMLMX project. I played a little bit with it and would like to offer a few modifications:
1. Amend boot scripts to fix booting - fix existing addresses and provide missing. Idea for values are taken from https://github.com/150balbes/LibreELEC.tv/tree/master-arm/projects/ARM/devices/ARMv7/bootloader/AMLMX/scripts
2. Modify kernel config to avoid "Invalid instruction" errors - based on RPi2 kernel config.

With these modifications, LE boots on a generic S805 Android box with old, outdated, Amlogic-modified u-boot. However, Kodi does not load, it's unable to open DRM; sound card missing - I may have missed something in kernel config.

If you find these useful, feel free to squash.

### CODE REVIEW

**Comment by chewitt** [comment]
Hi Mateusz, nice to see you :)

From a quick glance the boot/scripts changes look good but I'd like to take a longer look at the deconfig changes and test things in stages - I'll have a longer look over next weekend. Thanks for sharing the changes, and p.s. Feel free to drop into Slack sometime.

ping @dtechsrv

**Comment by chewitt** [comment]
I've pushed an updated branch which should have all the changes picked/sqashed in. Your kernel changes fixed boot for me but `CONFIG_REGULATOR_PWM=y` was missing and prevented lima from probing (Martin B spotted it). I have DRM now so Kodi starts, but I don't see anything on screen and it has issues opening a PCM device. Still progress though :)

**Comment by chewitt** [comment]
I pushed another update. Adding `CONFIG_DEVFREQ_THERMAL=y` fixes a probe issue with lima and I now have the Kodi home screen showing :)

**Comment by kszaq** [comment]
Thanks, I'll rebase later today. Yesterday I also got to a point with Kodi home screen showing. 

What device are you using for testing? My generic S805 box shows a distorted splash screen, later in Kodi it's all fine.

**Comment by chewitt** [comment]
I have an Odroid C1+ (S805) with a vintage u-boot that must find/use a boot.ini file; I wasn't able to make a bootable SD card for it yet but for testing have a frankenstein'd emmc module attached. Early boot is messed up but the Kodi home screen renders okay. There are canvas errors when trying to play media "Seems the overlay plane code crashes on meson8, probably scaling factor calculation" (narmstrong). Kodi is also throwing AESinkALSA errors although I have audio output.

I also have a WeTek Core (S812) which needs to see a kernel.img file for the SD card boot option to show up; but so far I wasn't able to get any further. I'll probably need to open the box and get UART pins soldered to find out where it's getting stuck, or spend time hunting for clues in the u-boot sources which I have somewhere (no history IIRC).

**Comment by chewitt** [comment]
This paste has the content for the factory u-boot environment for the WeTek Core http://ix.io/3NLB - it looks like it should pick up `aml_autoscript` via a recovery process, but I haven't gotten that to work yet.

**Comment by chewitt** [comment]
I got UART on the Core box and with a `kernel.img` file it picks up `aml_autoscript` and boots the kernel, but stalls and fails to complete boot (doesn't reach init). I believe Martin has booted one before so defconfig fettling is probably needed.

Edit: see https://pastebin.com/raw/rWTRKJtp

**Comment by kszaq** [comment]
WeTek Core has this u-boot feature where you can press power button on remote to boot OpenELEC from SD card. But for flexibility, I wouldn't use it but make it execute `s805_autoscript` instead - looks like this is what you did. 

Unfortunately I can't help with the stall...

**Comment by kszaq** [comment]
Closing as you merged everything. :)

**Comment by chewitt** [comment]
I made a `diff -y` comparison between the old LE 3.10 kernel and 5.16 and made some changes. I'm not sure exactly what items 'fixed' things but I can boot the Core box to Kodi home screen now: https://github.com/chewitt/LibreELEC.tv/commit/0eee885d87e658bade5a8b404c128d12899017cd

**Pull request closed without merging**
